# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mt6768-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter merlinx lancelot,$(TARGET_DEVICE)),)

endif
